DROP TABLE CHAT;

CREATE SEQUENCE CHATSEQ;

CREATE TABLE CHAT(
	CHATID NUMBER,
	CHATNAME VARCHAR2(20),
	CHATCONTENT VARCHAR2(100),
	CHATTIME DATE
);

SELECT * FROM CHAT;

INSERT INTO CHAT VALUES(CHATSEQ.NEXTVAL,'테스트','안녕하세요?', SYSDATE);

SELECT * FROM CHAT WHERE CHATTIME < SYSDATE ORDER BY CHATTIME;

SELECT * FROM CHAT WHERE CHATID > (SELECT MAX(CHATID)-10 FROM CHAT) ORDER BY CHATTIME;

SELECT * FROM CHAT WHERE CHATID > 11 ORDER BY CHATTIME;

SELECT GREATEST(MAX(CHATID)-12, 0)  FROM CHAT;