DROP TABLE EF_MEMBER;

CREATE TABLE EF_MEMBER (
	ID		VARCHAR2(20)		PRIMARY KEY,
	PW		VARCHAR2(20)		NOT NULL,
	NAME	VARCHAR2(20)		NOT NULL,
	EMAIL	VARCHAR2(30)		NOT NULL,
	ZONECODE	VARCHAR2(10)	NOT NULL,
	ADDR	VARCHAR2(100)		NOT NULL,
	ADDRETC	VARCHAR2(100)		NOT NULL,
	PHONE	VARCHAR2(13)		NOT NULL,
	GRADE	NUMBER(3)			NOT NULL,
	REGDATE	DATE				NOT NULL,
	DROPOUT	VARCHAR2(2)			NOT NULL
);

SELECT * FROM EF_MEMBER;

INSERT INTO EF_MEMBER 
values('user', '1234', '홍길동', 'gil@gil.com', '11176', 
'서울시 강남구 역삼동', 'kh교육원', '010-1111-2222', 1, sysdate, 'N');