DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ; --글 번호
CREATE SEQUENCE GROUPNOSEQ; -- 그룹 번호

--글번호 그룹번호 그룹순서 제목탭 제목 내용 작성자 작성일
--	1,	1,	1,		0,		TEST글, 관리자, 날짜
--	2,	2,	1,		0,		글하나, 테스터, ..
--	6,	2,	2,		1,	 	 ㄴRE: --
--	7,	2,	3,		2		  ㄴRE: --
--	4,	2,	4,		1,	 	 ㄴRE: --
--	5,	2,	5,		2		  ㄴRE: --
--	3,	3,	1,		0,		글둘,	테스터, ..

CREATE TABLE ANSWERBOARD(
	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(500) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL,
	DELCHECK VARCHAR2(2) NOT NULL
	
	CONSTRAINT ANSWERBOARD_CHK_DELCHECK CHECK(DELCHECK IN('Y', 'N'))
);

SELECT * FROM ANSWERBOARD ORDER BY GROUPNO DESC, GROUPSEQ;

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL,1,0,
'1번글 입니다','1번글 내용입니다.','관리자',SYSDATE,'N');

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1,0,
'2번글 입니다','2번글 내용입니다.','학생1',SYSDATE,'N');

--1번글입니다. (글번호 1번)에 답변 달기
--UPDATE : 부모의 글과 같은 그룹번호, 부모의 그룹순서보다 더 큰 그룹순서
--			그룹순서를 +1

UPDATE ANSWERBOARD SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=1)
 
 --INSERT
INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1)+1,
	'RE:1번글 입니다.',
	'1번글에 답변달기',
	'학생',
	SYSDATE,
	'N'
);

--RE:1번글입니다(글번호:3)에 답변달기
--UPDATE: 부모와 같은 그룹번호, 부모의 그룹순서보다 더 큰 그룹순서인 
-- 			글들을 찾아서 그룹순서 +1

UPDATE ANSWERBOARD 
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=3)
AND GROUPNO > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=3)
 
--INSERT
INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=3),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=3)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=3)+1,
	'RE:RE:1번글 입니다.',
	'RE:1번글에 답변 달아보자',
	'강사',
	SYSDATE,
	'N'
);


-------------------------------------------------

--UPDATE 3번 4번글 그룹순서+1
UPDATE ANSWERBOARD 
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=1)

--INSERT 1번 새로운 댓글 5번
--5,1,2,1
INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=1),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=1)+1,
	'RE:5번째답변',
	'RE:1번글에 답변 달아보자',
	'강사',
	SYSDATE
);

-------------------------------------------------

UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ+1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=5)

INSERT INTO ANSWERBOARD
VALUES(
	BOARDNOSEQ.NEXTVAL,
	(SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=5),
	(SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	(SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO=5)+1,
	'RE:RE:6번째답변',
	'RE:RE:6번째답변 내용',
	'학생',
	SYSDATE
);

--삭제 쿼리
UPDATE ANSWERBOARD SET DELCHECK = 'Y' WHERE BOARDNO=1;
