DROP SEQUENCE MVCSEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCSEQ;
CREATE TABLE MVCBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(500) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL
);

INSERT INTO MVCBOARD VALUES(MVCSEQ.NEXTVAL, '관리자', 'TEST제목', 'TEST내용', SYSDATE);
INSERT INTO MVCBOARD VALUES(MVCSEQ.NEXTVAL, '사용자', 'TEST제목', 'TEST내용', SYSDATE);

SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE FROM MVCBOARD ORDER BY SEQ DESC;


SELECT B.*
FROM (SELECT A.*, ROWNUM AS RNUM
		FROM (SELECT * FROM MVCBOARD ORDER BY SEQ DESC)A 
	)B
WHERE RNUM BETWEEN 11 AND 20

select * from mvcboard;
SELECT COUNT(*) AS TOTALCOUNT FROM MVCBOARD;